### ISSUE TITLE
Cant run project on windows.

### ISSUE THREAD

**Issue by mkudej** [eduardomoroni/react-clean-architecture#66]
So i did installation on windows like in readme.
1. go to authentication/core - npm install && npm run build
2. go to authentication/web - npm install && npm start

I get an error:

`auth-web@1.0.0 start D:\react-clean-architecture\authentication\web
react-scripts-ts start

undefined:21
  },
  ^

SyntaxError: Unexpected token } in JSON at position 545
    at JSON.parse (<anonymous>)
    at loadTsconfig (D:\react-clean-architecture\authentication\web\node_modules\tsconfig-paths\lib\tsconfig-loader.js:72:23)
    at loadSyncDefault (D:\react-clean-architecture\authentication\web\node_modules\tsconfig-paths\lib\tsconfig-loader.js:27:18)
    at tsConfigLoader (D:\react-clean-architecture\authentication\web\node_modules\tsconfig-paths\lib\tsconfig-loader.js:13:22)
    at configLoader (D:\react-clean-architecture\authentication\web\node_modules\tsconfig-paths\lib\config-loader.js:27:22)
    at Object.loadConfig (D:\react-clean-architecture\authentication\web\node_modules\tsconfig-paths\lib\config-loader.js:8:12)
    at new TsconfigPathsPlugin (D:\react-clean-architecture\authentication\web\node_modules\tsconfig-paths-webpack-plugin\lib\plugin.js:20:42)
    at Object.<anonymous> (D:\react-clean-architecture\authentication\web\node_modules\react-scripts-ts\config\webpack.config.dev.js:127:7)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\react-clean-architecture\authentication\web\node_modules\react-scripts-ts\scripts\start.js:39:16)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)`

**Comment by eduardomoroni** [comment]
Thanks for letting us know. I am checking on my end what could be happening.
To be upgrading a dependency version has fixed https://github.com/eduardomoroni/react-clean-architecture/commit/6fd58f3ca9a86f9c407550901ab0a4e88acfae65

Could you pull latest from master and try again?

**Comment by eduardomoroni** [comment]
@mkudej did you have the chance of trying out again?

**Comment by Brahua** [comment]
Hi @eduardomoroni . I have the same problem. Any solution?

**Comment by eduardomoroni** [comment]
Have you tried after the previous commit? Master should be fine now, could
you try again and let me know? Please make sure you use npm ci (don't use
yarn).

**Comment by mkudej** [comment]
Hi, i will check it tomorrow.

**Comment by eduardomoroni** [comment]
Did it work guys?
